[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | __pycache__
  | fastembed_cache
  | reranker_cache
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["agents", "config", "models", "tools", "utils", "workflow_builders", "prompt_engineering"]
skip_glob = ["*/__pycache__/*", "*/fastembed_cache/*", "*/reranker_cache/*"]

[tool.coverage.run]
source = ["."]
omit = [
    "tests/*",
    "*/tests/*",
    "*/__pycache__/*",
    "*/fastembed_cache/*",
    "*/reranker_cache/*",
    "legacy/*",
    "*/legacy/*",
    "venv/*",
    ".venv/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.bandit]
exclude_dirs = ["tests", "legacy"]
skips = ["B101", "B601"]  # Skip assert_used and shell_injection for test files